name: Publish docker image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
   
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push public image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: services
          push: true
          file: services/Dockerfile.public
          tags: uboot/sonja-public:latest

      - name: Build and push crawler image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: services
          push: true
          file: services/Dockerfile.crawler
          tags: uboot/sonja-crawler:latest

      - name: Build and push scheduler image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: services
          push: true
          file: services/Dockerfile.scheduler
          tags: uboot/sonja-scheduler:latest

      - name: Build and push agent image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: services
          push: true
          file: services/Dockerfile.agent
          tags: uboot/sonja-agent:latest
  